EcomProj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ProductApp.urls')),
    path('accounts/', include('LoginApp.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

LoginApp/urls.py
from django.urls import path
from LoginApp import views

app_name = 'LoginApp'

urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.editprofile_view, name='profile'),
]

ProductApp/urls.py
from django.urls import path
from ProductApp import views

app_name = 'ProductApp'

urlpatterns = [
    path('', views.home_view, name='home'),
    path('search/', views.search_view, name='search'),
]

LoginApp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserprofileModel(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='user_profile')
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)
    description = models.TextField(blank=True)
    full_name = models.CharField(max_length=264, blank=True)
    date_of_birth = models.DateField(blank=True, null=True)
    website = models.URLField(blank=True)
    facebook = models.URLField(blank=True)

    def __str__(self) -> str:
        return self.user 

ProductApp/models.py
from django.db import models

# Create your models here.

class CategoryModel(models.Model):
    title = models.CharField(max_length=20)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name_plural = "Categories"


class BrandModel(models.Model):
    title = models.CharField(max_length=20)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name_plural = "Brands"


class WarrantyModel(models.Model):
    year = models.PositiveIntegerField(max_length=10)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.year)
    
    class Meta:
        verbose_name_plural = "Warranties"
        ordering = ['year']


class ProductModle(models.Model):
    mainimage = models.ImageField(upload_to='Products')
    name = models.CharField(max_length=264)
    category = models.ForeignKey(CategoryModel, on_delete=models.CASCADE, related_name='category')
    brand = models.ForeignKey(BrandModel, on_delete=models.CASCADE)
    warranty = models.ForeignKey(WarrantyModel, on_delete=models.CASCADE)
    preview_text = models.TextField(max_length=200, verbose_name='Preview Text')
    detail_text = models.TextField(max_length=1000, verbose_name='Description')
    price = models.FloatField()
    old_price = models.FloatField(default=0.00)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
         return self.name
    
    class Meta:
        ordering = ['-created']

LoginApp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from LoginApp.models import UserprofileModel

class CreateUserForm(UserCreationForm):
    email = forms.EmailField(required=True, label="", widget=forms.TextInput(attrs={'placeholder':'Email'}))
    username = forms.CharField(required=True, label="", widget=forms.TextInput(attrs={'placeholder':'Username'}))
    password1 = forms.CharField(required=True, label="", widget=forms.PasswordInput(attrs={'placeholder':'Password'}))
    password2 = forms.CharField(required=True, label="", widget=forms.PasswordInput(attrs={'placeholder':'Password Confirmation'}))

    class Meta:
        model = User
        fields = ('email', 'username', 'password1', 'password2')


class EditProfile(forms.ModelForm):
    date_of_birth = forms.DateField(widget=forms.TextInput(attrs={'type':'date',}))

    class Meta:
        model = UserprofileModel
        exclude = ('user',)

ProductApp/forms.py
from django import forms
from ProductApp.models import ProductModle, CategoryModel, BrandModel, WarrantyModel

# Forms Stat here

class ProductSearchForm(forms.Form):
    category = forms.ModelChoiceField(queryset=CategoryModel.objects.all(), empty_label="All Categories", required=False)
    brand = forms.ModelChoiceField(queryset=BrandModel.objects.all(), empty_label="All Brands", required=False)
    warranty = forms.ModelChoiceField(queryset=WarrantyModel.objects.all(), empty_label="All Warranties", required=False)
    min_price = forms.IntegerField(label='Min Price', required=False)
    max_price = forms.IntegerField(label='Max Price', required=False)

LoginApp/views.py
from django.shortcuts import render, HttpResponseRedirect, get_object_or_404
from django.urls import reverse

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required

from LoginApp.models import UserprofileModel
from LoginApp.forms import CreateUserForm, EditProfile

#Pass formate 1234@username

# Create your views here.

def signup_view(request):
    form = CreateUserForm()
    registered = False

    if request.method == 'POST':
        form = CreateUserForm(data=request.POST)

        if form.is_valid():
            user = form.save()
            registered = True
            user_profile = UserprofileModel(user=user)
            user_profile.save()
            
            return HttpResponseRedirect(reverse('LoginApp:login'))

    return render(request, 'LoginApp/signup.html', context={'title':'Signup', 'form':form, 'registered':registered})

def login_view(request):
    form = AuthenticationForm()

    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)

        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            
            user = authenticate(username=username, password=password)
            
            if user is  not None:
                login(request, user)
                return HttpResponseRedirect(reverse('ProductApp:home'))

    return render(request, 'LoginApp/login.html', context={'title':'Login', 'form':form})

@login_required
def editprofile_view(request):
    current_user = get_object_or_404(UserprofileModel, user=request.user)
    form = EditProfile(instance=current_user)

    if request.method == 'POST':
        form = EditProfile(request.POST, request.FILES, instance=current_user)
        
        if form.is_valid():
            form.save(commit=True)
            form = EditProfile(instance=current_user)
            return HttpResponseRedirect(reverse('LoginApp:profile'))

    return render(request, 'LoginApp/profile.html', context={'title':'Profile', 'form':form})

@login_required
def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('ProductApp:home'))

ProductApp/views.py
from django.shortcuts import render, HttpResponse
from django.http import JsonResponse
from django.template.loader import render_to_string
from ProductApp.models import ProductModle
from ProductApp.forms import ProductSearchForm

# Create your views here.

def home_view(request):
    products = ProductModle.objects.all() 
    form = ProductSearchForm(request.GET)

    context = {
        'products': products,
        'title': 'HOME',
        'form': form,
    }

    return render(request, 'ProductApp/home.html', context=context)

def search_view(request):
    products = ProductModle.objects.all()    
    products_data = list(products.values())

    context = {
        'products': products_data,
    }

    return JsonResponse(context, safe=False)

templates/LoginApp/login.html
{% extends 'index.html' %}
{% load crispy_forms_tags %}

{% block title_block %} {{ title }} {% endblock %}

{% block body_block %}
<div class="container">
    <h2 class="mt-5 mb-3">Login To Your Account</h2>
<form method="POST">
    {{ form|crispy }}
    {% csrf_token %}
    <button class="btn btn-success btn-sm" type="submit">LOGIN</button>
</form>
<hr>
<br>
<p class="mb-5">Already have an account? <a href="{% url 'LoginApp:signup' %}">Signup</a></p>
</div>
{% endblock %}

templates/LoginApp/profile.html
{% extends 'index.html' %}
{% load crispy_forms_tags %}

{% block title_block %} {{ title }} {% endblock %}

{% block body_block %}
<div class="container">
    <h2 class="mt-5">Your profile</h2>
<form method="POST">
    {{ form|crispy }}
    {% csrf_token %}
    <button class="btn btn-success btn-sm" type="submit">SAVE</button>
</form>
<hr>
</div>
{% endblock %}

templates/LoginApp/signup.html
{% extends 'index.html' %}
{% load crispy_forms_tags %}

{% block title_block %} {{ title }} {% endblock %}

{% block body_block %}
<div class="container">
    <h2 class="mt-5">Create A New Account</h2>
<form method="POST">
    {{ form|crispy }}
    {% csrf_token %}
    <button class="btn btn-success btn-sm" type="submit">SIGNUP</button>
</form>
<hr>
<p>Already have an account? <a href="{% url 'LoginApp:login' %}">Login</a></p>
</div>
{% endblock %}

templates/ProductApp/home.html
{% extends 'index.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title_block %} {{ title }} {% endblock %}

{% block body_block %}

<div class="banner">
    <img class="img img-fluid w-100" src="{% static 'img/banner.png' %}" alt="">
</div>

<div class="container">
    <div class="row">
        <div class="col-md-3">
            <div class="row">
                <div class="col-md-12">
                    <h2 class="mt-md-5 text-center">Search Products</h2>
                    <hr>
                    <!-- <form class="" method="get" action=""> -->
                        {% csrf_token %}
                        <div class="mb-2">
                            <label class="form-label">Category : </label>
                            <select class="form-select" name="category" id="category">
                                <option value="" selected>All Categories</option>
                                {% for category in form.category.field.queryset %}
                                    <option value="{{ category.pk }}">{{ category }}</option>
                                {% endfor %}
                            </select>
                        </div>

                        <div class="mb-2">
                            <label class="form-label">Brands : </label>
                            <select class="form-select" name="brand" id="brand">
                                <option value="" selected>All Brands</option>
                                {% for brand in form.brand.field.queryset %}
                                <option value="{{ brand.pk }}">{{ brand }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        
                        <div class="mb-2">
                            <label class="form-label" for="">Warranty : </label>
                            <select class="form-select" name="warranty">
                                <option value="" selected>All Warranties</option>
                                {% for warranty in form.warranty.field.queryset %}
                                <option value="{{ warranty.pk }}">{{ warranty }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        
                        <div class="mb-2">
                            <label class="form-label" for="">Min Price : </label>
                            <input class="form-control" type="number" value="{{ form.min_price.value }}">
                        </div>

                        <div class="mb-2">
                            <label for="">Max Price : </label>
                            <input class="form-control" type="number" value="{{ form.max_price.value }}">
                        </div>

                        <div class="text-center">
                            <button class="btn btn-success" id="get_data">SEARCH</button>
                        </div>
                    <!-- </form> -->
                    <hr>
                </div>
            </div>
        </div>
        <div class="col-md-9">
            <h2 class="mt-5 text-center">Featured Product</h2>
            <hr>
            <div class="row" id="search-results-holder">
            </div>
            <div class="row" id="search-results">
                {% for product in products %}
                <div class="col-md-6 col-sm-12 col-lg-3" id="search-results-container">
                    <figure class="card card-product">
                        <div class="img-wrap">
                            <img src="/media/{{ product.mainimage }}" class="img img-fluid" alt="" style="width: 100%; height: 300px;">
                        </div>
                        <figcaption class="info-wrap">
                            <h6 class="title"><a href="#">{{ product.name }}</a></h6>
                            <div class="action-wrap">
                                <div class="price-wrap h5">
                                    <span class="price-new">Price: &#2547; {{ product.price|floatformat:2 }}</span>
                                    <br>
                                    <span class="price-old">Old Price: &#2547; <strike>{{ product.old_price|floatformat:2 }}</strike>
                                    </span>
                                </div>
                            </div>
                        </figcaption>
                    </figure>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

{% endblock %} 

templates/footer.html
<footer class="bg-dark">
    <div class="container">
        <div class="row">
            <div class="col-12 text-white text-center pt-3">
                <p>All Copyright is preserved © To Md Sha Newaz</p>
                <p class="" id="dev_text">Developed by <a class="text-success" href="https://mdshanewaz.github.io/DarkBlackFire" target=”_blank”>Dev SAWON</a></p>
            </div>
        </div>
    </div>
</footer>

templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title_block %}E-Commerence{% endblock %}</title>
    <link rel="shortcut icon" href="{% static 'img/favicon.png' %}" type="image/x-icon">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    {% include 'navbar.html' %}

    <div class="container">
        <div class="messages mt-2">
            {% if messages %}
                {% for message in messages %}
                    <div {% if message.tags %} class="alert alert-{{message.tags}}" {% endif %} role="alert">
                        {{ message }}
                        <button type="button" class="btn close" data-bs-dismiss="alert" aria-label="Close" style="float: right;">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                {% endfor %}
            {% endif %} 
        </div>
    </div>

    {% block body_block %}

    {% endblock %}

    {% include 'footer.html' %}

    <script src="https://code.jquery.com/jquery-3.7.1.slim.min.js" integrity="sha256-kmHvs0B+OpCW5GVHUNjv9rOmY0IvSIRcf7zGUDTDQM8=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js" integrity="sha512-2rNj2KJ+D8s1ceNasTIex6z4HWyOnEYLVC3FigGOmyQCZc2eBXKgOxQmo3oKLHyfcj53uz4QMsRCWNbLd32Q1g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script src="{% static 'js/scripts.js' %}"></script>
</body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
      <a class="navbar-brand" href="{% url 'ProductApp:home' %}">Navbar</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          {% if request.user.is_authenticated %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <i class="fa-solid fa-user-tie"></i> {{ request.user.profile.username }}</a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              
              <li><a class="dropdown-item" href="{% url 'LoginApp:profile' %}">Profile</a></li>
                <div class="dropdown-divider">
                </div>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="{% url 'LoginApp:logout' %}">Logout</a></li>
            </ul>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="btn btn-primary" href="{% url 'LoginApp:login' %}">Login</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
</nav>